### ISSUE TITLE
Use a Logger

### ISSUE THREAD

**Issue by pjambet** [harrystech/seed_migration#38]
Use a logger instead of `puts`/`p`, this would allow users to filter out logs with more granularity.

Suggestion, use ruby's [Logger](http://ruby-doc.org/stdlib-2.2.2/libdoc/logger/rdoc/Logger.html) or [log4r](https://github.com/colbygk/log4r)

**Comment by pjambet** [comment]
Closing since it seems like it's been mostly addressed by #58 but also because I believe that this gem is not maintained anymore

**Comment by pboling** [comment]
@pjambet Do you know anyone at Harry's that can help get this gem moved to a new home where it would be maintained? https://github.com/harrystech/seed_migration/issues/69

**Comment by pjambet** [comment]
Hey @pboling 👋, great question and tbh, not sure, @BasilDarwaza if I had to guess, maybe? 🤷‍♂️ If we don't get a reply here in a few days I can see and try to reach out to figure out who could help you.
