### ISSUE TITLE
check pending?

### ISSUE THREAD

**Issue by aemadrid** [harrystech/seed_migration#39]
Any way to check for pending seed migrations? Like with schema we can do this:

ActiveRecord::Migration.check_pending!

Any way to do the same with seed migrations?

**Comment by pjambet** [comment]
Hey Adrian,

That's a good idea, but as you may already know, this feature is not implemented yet.
I'll keep that in mind if I have time to work on this but can't make any promises at the moment.

As usual, feel free to send a PR if you want, I'd be happy to review it.

Cheers,

**Comment by pjambet** [comment]
Version 1.2.0 was released yesterday, check #46 for more details.

**Comment by pjambet** [comment]
1.2.0 was released yesterday with the changes from #46
