### ISSUE TITLE
Display status of data migrations

### ISSUE THREAD

**Issue by tbloncar** [harrystech/seed_migration#40]
I've enjoyed ActiveRecord's `db:migrate:status` task that displays the status of schema migrations. I'm wondering if there's interest in a `seed:migrate:status` or `seed:status` task that does the same for data migrations. I've [implemented this on my fork](https://github.com/tbloncar/seed_migration/tree/tb-rake-seed-status) and am happy to submit a PR if there's interest. ~~I also assume that it'd be fairly easy to tackle #39 in the process. (This does address the issue of pending migrations at some level, but it doesn't offer the `check_pending!` method and exception behavior.)~~ I went ahead and implemented `.check_pending!`, as well.

This is what the output (format copied directly from AR's task) looks like.

```
database: seed-migrationdevelopment

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20160114153832  Add users
  down    20160114153843  Add more users
  down    20160114153851  Add even more users
```

**Comment by pjambet** [comment]
Hey @tbloncar 

This is a great idea. You said that you already work on this, do you want to open a pull request so that we can merge this here?

Thanks again for you collaboration!

**Comment by tbloncar** [comment]
@pjambet: Yep. Happy to. I'll open a PR as soon as I get the chance. Appreciate the feedback.

**Comment by pjambet** [comment]
Version 1.2.0 was released yesterday, thanks again!

**Comment by ain** [comment]
Sounds great!

@pjambet I missed it completely since the tag was missing :)
