### ISSUE TITLE
Deploy with Capistrano

### ISSUE THREAD

**Issue by vill** [harrystech/seed_migration#52]
if I add hook `after 'deploy:updated', 'seed:migrate'` for `Capistrano` to an existing project and run `cap production deploy` then I get this error:
```
rails aborted!
Don't know how to build task 'seed:migrate' (see --tasks)
```
I think this error occurs because tasks [`seed:migrate`](https://github.com/harrystech/seed_migration/blob/master/lib/capistrano/seed_migration_tasks.rb#L5) and [`seed:rollback`](https://github.com/harrystech/seed_migration/blob/master/lib/capistrano/seed_migration_tasks.rb#L16) used `current_path` instead of `release_path` and `Capistrano` runs this tasks in the previous version of the application that does not have migrations in `db/data/*` and `seed:*` tasks.

**Comment by pjambet** [comment]
Hi,

Sorry for the late reply, I don't exactly know what I changed but I apparently muted the notifications from this repo by mistake and didn't notice new issues opened in the last 6 months. Sorry about that.

The capistrano feature was a contribution from someone else and is something that I never used so I can't really help with this.

I don't have a lot of time at the moment, but feel free to open a PR and I'll happily review it.

Thank you!

**Comment by pjambet** [comment]
I just deployed 1.2.3 with your PR #57 . Marking this as fixed for now. Feel free to reopen if you encounter other issues.

Thank you again!
