### ISSUE TITLE
'Directly inheriting from ActiveRecord::Migration is not supported' on rails 5.1

### ISSUE THREAD

**Issue by mlabarca** [harrystech/seed_migration#56]
When running generator to setup initial migration and then attempting to migrate, it fails with the following: 

> rake aborted!

> StandardError: An error has occurred, this and all later migrations canceled:
> 
> Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
> 
>   class CreateDataMigrations < ActiveRecord::Migration[4.2]

This on rails 5.1.1.  This is fixed easily by adding 5.1 at the end so it ends up just like this: 
`class CreateDataMigrations < ActiveRecord::Migration[5.1]`

**Comment by pjambet** [comment]
Hi,

Thanks for the report. I don't think I'll have time to send a fix, but feel free to open a PR, I'll happily review it.

Thanks again!

**Comment by pjambet** [comment]
I added 5.1 to the build matrix on travis and pushed a few fixes that should help with this. Looks like this is fixed, feel free to reopen if you encounter other issues.

Thank you!

**Comment by mlabarca** [comment]
Thank you! Sorry i couldnt help you fix it myself :(. What pr fixed it?
