### ISSUE TITLE
registering only some instances of a model

### ISSUE THREAD

**Issue by modosc** [harrystech/seed_migration#63]
we've run into a situation where we need certain (but not _all_) records managed by seed migrations. ideally we'd be able to do something like:
```
SeedMigration.register User do
  only Proc.new { |user| user.admin? }
end
```
do you see any reason this wouldn't be doable? would you be open to a pr for it?

**Comment by pjambet** [comment]
Hi @modosc 

Sorry for the late reply.

This sounds like a good idea, feel free to send a PR and I will happily review it.
